/** Sector examples are proposals, not claims of past client results. */
export const INDUSTRIES = [
  {
    slug: 'bridal-marketing-toronto', name: 'Bridal & alterations',
    title: 'Bridal marketing in Toronto',
    description: 'Reels, Meta ads and enquiry-focused websites for Toronto bridal boutiques and alterations studios. Joseph The Great: CAD $700–$1,000/month, ad spend separate.',
    intro: 'Help a bride understand your work before she asks for a fitting. I make short videos, Meta ads and websites for bridal boutiques and alterations studios in Toronto and the GTA.',
    problem: 'A beautiful dress photo cannot explain what an alteration involves, how early to enquire or whether you can handle a particular gown. Those unanswered questions are useful subjects for content — and useful information to put next to an enquiry button.',
    ideas: [
      { title: 'Show the decision behind the detail', text: 'A close-up of a hem, bustle or fit adjustment, with a short explanation from the person doing the work. Film with the client’s permission and explain what changed, without implying every gown needs the same treatment.' },
      { title: 'Make the next step specific', text: 'Send interested viewers to a fitting enquiry with space for a wedding date, the service needed and a way to reply. Explain what the studio needs to see before quoting.' },
      { title: 'Test one appointment offer', text: 'Use a locally targeted Meta messaging campaign around a service the studio has capacity to deliver. Review relevant enquiries and booked fittings separately from views or message counts.' },
    ],
    need: 'Your alteration services, appointment process, availability, filming permissions and examples of questions brides ask before booking.',
    measure: 'Relevant enquiries → fitting appointments → completed paid work. Record ad spend separately from the creative fee.',
    proofSlug: 'dream-alteration', proof: 'Dream Alterations is the directly relevant bridal case: the saved Meta screenshot shows CAD $214.86 spent and 59 conversations started, averaging $3.64 each. Nine leads are reported in the project notes. Bookings and revenue were not tracked in this case.',
    faq: { question: 'Do you only work with bridal businesses?', answer: 'No. Bridal is one area with a published local case. I also offer creative work for other Toronto businesses; the scope and success measure depend on what they sell.' },
  },
  {
    slug: 'beauty-salon-marketing-toronto', name: 'Beauty & salons',
    title: 'Beauty salon marketing in Toronto',
    description: 'Short-form content, Meta ads and booking-page work for Toronto beauty salons. Work directly with Joseph. CAD $700–$1,000/month depending on scope.',
    intro: 'Turn your salon’s skill into content people can understand and a clear route to an appointment. I offer reels, Meta ads and website work for Toronto hair, nail, lash and beauty businesses.',
    problem: 'A feed of finished looks can leave a new customer unsure which service to choose, how much time to set aside or who will be doing the work. Start with one service you want to book more often and explain it clearly.',
    ideas: [
      { title: 'Explain one service from the chair', text: 'Show the consultation, process and finished result with permission. Use consistent lighting for before-and-after footage, and say who the service is suited to instead of promising an identical result for everyone.' },
      { title: 'Put the booking details together', text: 'Bring the service description, starting price where appropriate, expected duration and booking link onto one page. Use the salon’s existing booking system if it already works.' },
      { title: 'Promote actual availability', text: 'Build a reel or local ad around an appointment type and availability the owner confirms. The message should name the service and location rather than relying on a vague “treat yourself” caption.' },
    ],
    need: 'The service to promote, pricing, booking link, staff availability and permission to film staff and customers.',
    measure: 'Service-specific enquiries → appointments booked → appointments attended. Reach is a separate creative measure.',
    proofSlug: 'dream-alteration', proof: 'I do not currently publish a beauty-salon results case. The closest appointment-business example is Dream Alterations: 59 Meta conversations from CAD $214.86 in spend. That is bridal evidence, not a salon booking forecast.',
    faq: { question: 'Can you work with my existing booking page?', answer: 'Yes. Website work can focus on the path to your existing booking system. We agree on the actual changes before starting; a new website is not automatically part of every monthly scope.' },
  },
  {
    slug: 'gym-marketing-toronto', name: 'Gyms & fitness',
    title: 'Gym marketing in Toronto',
    description: 'Reels, Meta ads and trial-enquiry pages for Toronto gyms and fitness studios. See the Spartan Gymnastics reach case. CAD $700–$1,000/month; ads separate.',
    intro: 'Give someone a reason to try their first session. I make reels, Meta ads and website content for gyms, fitness studios and gymnastics businesses in Toronto and the GTA.',
    problem: 'Existing members already know the room and the coaches. A new visitor may be wondering whether beginners are welcome, what a first session looks like and how to choose a class. Content can answer those questions before asking for a trial.',
    ideas: [
      { title: 'Film the first-visit experience', text: 'Follow the route from the front door to a beginner session. Show the coach, what to bring and the next available class, using your real schedule and permission from anyone appearing in the footage.' },
      { title: 'Give each programme a clear next step', text: 'A beginner trial, a kids’ camp and personal training need different information. Link a piece of content to the relevant programme rather than making every visitor search a general timetable.' },
      { title: 'Test a local introduction', text: 'Try one creative angle and one trial offer in a defined service area. Keep the trial terms clear and ask staff to record which enquiries became attended sessions.' },
    ],
    need: 'The programme to promote, who it suits, timetable, trial terms, filming permissions and a person who can reply to enquiries.',
    measure: 'Trial enquiries → trials attended → memberships or enrolments. A high view count does not establish any of those outcomes.',
    proofSlug: 'spartan-gymnastics', proof: 'The published Spartan Gymnastics case records 9,224 views in two weeks, 74.9% from non-followers and no ad spend. It demonstrates content reach; enrolments were not measured. It is not evidence of paid gym membership growth.',
    faq: { question: 'Do the gymnastics results guarantee new gym members?', answer: 'No. The saved case measures views and audience reach. For a membership campaign, we would agree how to track trial attendance and membership sales before calling it successful.' },
  },
  {
    slug: 'restaurant-marketing-toronto', name: 'Restaurants & cafés',
    title: 'Restaurant marketing in Toronto',
    description: 'Reels, local Meta ads and website work for Toronto restaurants and cafés. Clear menus and reservation or ordering paths. CAD $700–$1,000/month; scope agreed.',
    intro: 'Make the food memorable and the practical details easy to find. I offer short videos, local Meta ads and website work for restaurants and cafés in Toronto.',
    problem: 'A food video can get attention from anywhere. A local diner still needs to know where you are, when you are open, what is on the menu and how to reserve or order. The creative and that practical information need to agree.',
    ideas: [
      { title: 'Build a story around one dish', text: 'Film a signature dish from preparation to the table. Put the restaurant name and neighbourhood in the piece and give the viewer a specific reason to visit, based on what you actually serve.' },
      { title: 'Choose the destination before the ad', text: 'A lunch special can lead to a current menu; a dinner occasion can lead to reservations. Keep hours, availability and pricing accurate on the destination page.' },
      { title: 'Make the phone journey easy', text: 'Check whether the menu is readable on a phone and whether reservation or ordering links work. Agree a focused set of website changes around the route diners will actually use.' },
    ],
    need: 'Your current menu, hours, location, reservation or ordering link, the offer to feature and a filming window that works for the kitchen.',
    measure: 'Reservation or order enquiries → confirmed bookings or orders. Report link clicks separately when completed transactions cannot be attributed.',
    proofSlug: 'quantlarper', proof: 'I do not currently publish a restaurant client case. My own Quantlarper project shows short-form creative reach: a saved 30-day snapshot reports 1.2 million views with no ad spend. That audience result does not prove restaurant visits or orders.',
    faq: { question: 'Will views tell me whether people visited?', answer: 'No. Views measure exposure. Reservations, tracked orders or a consistently recorded in-store response give more useful evidence of customer action. The measurement plan depends on your existing systems.' },
  },
  {
    slug: 'retail-marketing-toronto', name: 'Shops & local retail',
    title: 'Retail marketing in Toronto',
    description: 'Product reels, local Meta ads and website work for independent Toronto shops. Work directly with Joseph at CAD $700–$1,000/month depending on scope.',
    intro: 'Show people what is worth coming in for. I offer product videos, Meta ads and website work for independent shops and local retail businesses in Toronto.',
    problem: 'A product photo shows what is on the shelf. A useful video can show how it works, how to choose between options or why someone would want to see it in person. The next step should match whether the shop sells in-store, online or through enquiries.',
    ideas: [
      { title: 'Demonstrate a product decision', text: 'Compare two genuinely different options, show the scale or fit, or answer a question staff hear often. Use actual stock and prices rather than building the idea around a product that is not available.' },
      { title: 'Connect discovery to availability', text: 'A local ad can lead to a product page, a stock enquiry or clear store details. Agree one route first so staff can respond consistently when someone asks about the featured item.' },
      { title: 'Make a small launch understandable', text: 'For a new collection or in-store event, create a concise story with the date, location and what is available. Only describe a limited quantity or deadline when it is real.' },
    ],
    need: 'The products to feature, stock and pricing, store location, the preferred sales route and permission to film inside the shop.',
    measure: 'Product enquiries or tracked visits to a product page → orders or recorded in-store purchases. Do not count every video viewer as a potential local buyer.',
    proofSlug: 'joeroblox85', proof: 'I do not currently publish a retail-sales case. My own YouTube channel, Joeroblox85, has a saved analytics snapshot with 33.1 million lifetime views. It demonstrates audience-building experience, not sales generated for a Toronto store.',
    faq: { question: 'Do I need a new online store?', answer: 'Not necessarily. The work can support an existing shop, product page or enquiry process. A complete ecommerce build needs its own agreed scope; it is not implied by the monthly price range.' },
  },
] as const;

export const industryBySlug = (slug: string) => INDUSTRIES.find((item) => item.slug === slug);
